### ISSUE TITLE
Different byron proxies for the same network do not use the same chain?

### ISSUE THREAD

**Issue by erikd** [input-output-hk/ouroboros-network#1096] opened 2019-10-02 04:50 UTC
In order to sync mainnet more quickly I configured my node to use a locally running byron proxy using:
```
$ nix-build -A scripts.mainnet.node -o launch_mainnet_node --arg customConfig '{ useProxy = true; 
}'
$ ./launch_mainnet_node
```
which allowed me to sync all the way to the current chain tip.

If I now rebuild it to use the default remote proxy and then run that using:
```
$ nix-build -A scripts.mainnet.node -o launch_mainnet_node 
$ ./launch_mainnet_node
```
I get a "ForkTooDeep" error:
```
[iohk.cardano.node.CoreId 0.ChainSyncClient:Warning:82] [2019-10-02 04:48:21.21 UTC] {"exception":"ForkTooDeep (Point {getPoint = Origin}) (Tip {tipPoint = Point {getPoint = At (Block {blockPointSlot = SlotNo {unSlotNo = 1500206}, blockPointHash = ByronHash {unByronHash = AbstractHash d814b9e4d6cf69f751340563dc2c9875400ac700c9f45416551b25dfa0743d7d}})}, tipBlockNo = BlockNo {unBlockNo = 1499903}})","kind":"ChainSyncClientEvent.TraceException"}
```
and it fails to sync.

If I then rebuild (using top `nix-build` command) to use my local byron proxy it is perfectly happy to continue on the existing chain.

I have already confirmed that these are using the same genesis hash and genesis JSON file.

**Comment by erikd** [comment] 2019-10-02 04:59
The only difference between the two instances of the `launch_mainnet_node` script are the `topology.yaml` files and the diff of these two files is:
```
$ diff -u /nix/store/g8fb0sjaq39dbxnvv35dqcwafgvc26vx-topology.yaml /nix/store/phsaw3fp33f4k64qc258z8dsn1mm3vn1-topology.yaml
--- /nix/store/g8fb0sjaq39dbxnvv35dqcwafgvc26vx-topology.yaml   1970-01-01 10:00:01.000000000 +1000
+++ /nix/store/phsaw3fp33f4k64qc258z8dsn1mm3vn1-topology.yaml   1970-01-01 10:00:01.000000000 +1000
@@ -1 +1 @@
-[{"nodeAddress":{"addr":"127.0.0.1","port":3001},"nodeId":0,"producers":[{"addr":"18.185.45.45","port":3001,"valency":1}]}]
+[{"nodeAddress":{"addr":"127.0.0.1","port":3001},"nodeId":0,"producers":[{"addr":"127.0.0.1","port":7777,"valency":1}]}]
```

**Comment by coot** [comment] 2019-10-02 08:16
@erikd @karknu is doing the same on a regular basis.  Expectedly, the local proxy is ahead of the remote one.  We don't yet have exception handling in place, changes to `ouroboros-network` are queued for review (#902, #939) and there's some work for the consensus team to be done on top of that.

**Comment by disassembler** [comment] 2019-10-02 12:46
Your second case actually isn't a proxy, it's a remote cardano-node.

**Comment by mrBliss** [comment] 2019-11-07 14:39
@erikd is this still relevant?

**Comment by edsko** [comment] 2019-11-08 09:43
@coot , you write

> Expectedly, the local proxy is ahead of the remote one.

But why is that expected?

**Comment by mrBliss** [comment] 2019-11-08 09:44
_If_ there is a consensus problem, then this ticket is high priority.

**Comment by edsko** [comment] 2019-11-12 09:21
@erikd says he cannot reproduce this anymore. Closing this. Feel free to reopen if this turns out still to be a problem.

**Closed by edsko** 2019-11-12 09:21 UTC
Labels: consensus, priority high
