### ISSUE TITLE
Switch header and body validation in `applyExtLedgerState`

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1579] opened 2020-02-05 08:34 UTC
At the moment, `applyChainState` insists that it must be passed the _updated_ ledger view, and so `applyExtLedgerState` validates the body before validating the header. This is however quite confusing, _especially_ because _we have already validated that header without having seen the body_ (for blocks that we download: the chain sync client validates the header first). The trick there of course is that chain validation uses the _anachronistic_ ledger view to validate the header. We should do the same in `applyExtLedgerState`, making these two things more consistent with each other. `protocolLedgerView` can then go altogether.

by using anachronistic ledger view for the header

**Comment by edsko** [comment] 2020-02-05 09:19
Marking this as medium priority despite it also being technical debt, because it makes the relation to the spec a bit harder to see.

**Comment by mrBliss** [comment] 2020-03-13 13:24
Duplicate of #1771, fixed by #1775

**Closed by mrBliss** 2020-03-13 13:24 UTC
Labels: byron, consensus, priority medium, technical debt
