### ISSUE TITLE
Explain failure in `ouroboros-storage: Storage: HasFS: HasFS: q-s-m` test

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/ouroboros-network#943] opened 2019-08-21 13:08 UTC
Looks like the `ouroboros-storage: Storage: HasFS: HasFS: q-s-m` test failed in https://hydra.iohk.io/build/1070633/nixlog/1. It's on a work in progress branch for #773, but I'm pretty sure there are no relevant differences with `912c0639 - (origin/master, origin/bors/staging, origin/HEAD) Merge #924` from `master`.

This ticket is to assess that failure and maybe provide a fix.

**Comment by mrBliss** [comment] 2019-08-22 07:52
Ah, this is mingw32, so this is a duplicate of #882.

**Closed by mrBliss** 2019-08-22 07:52 UTC
Labels: bug, consensus
