### ISSUE TITLE
net_impl_multiplexing_serialization

### ISSUE THREAD

**Issue by boothead** [input-output-hk/ouroboros-network#121] opened 2018-12-12 14:50 UTC
# Description

Design and implement the multiplexing, versioning, serialization and framing scheme for running the mini-protocols on a single bearer channel, in simulation

# Business value

<Explain how the epic fits into the bigger picture>

# Estimate

<Rough estimate of mandays required to complete epic>

**Comment by coot** [comment] 2018-12-17 10:54
@boothead this seems to be a duplicate of #59

**Closed** 2019-03-07 09:51 UTC
Labels: networking
