### ISSUE TITLE
Rapid cardano-node restart causes node to crash due to file locking

### ISSUE THREAD

**Issue by nikolaglumac** [input-output-hk/ouroboros-network#1903] opened 2020-04-05 17:31 UTC
Rapid cardano-node restarts crash node with following error messages:
```
FsError {fsErrorType = FsInsufficientPermissions, fsErrorPath = C:\Users\patk3\AppData\Roaming\Daedalus Flight\chain\protocolMagicId, fsErrorString = "The process cannot access the file because another process has locked a portion of the file.", fsErrorNo = Just (Errno 13), fsErrorStack = [("ioToFsError",SrcLoc {srcLocPackage = "ouroboros-consensus-0.1.0.0-YOEuCz1reE2yr064xJ6cY", srcLocModule = "Ouroboros.Consensus.Storage.FS.IO", srcLocFile = "src/Ouroboros/Consensus/Storage/FS/IO.hs", srcLocStartLine = 86, srcLocStartCol = 41, srcLocEndLine = 86, srcLocEndCol = 68}),("handleError",SrcLoc {srcLocPackage = "ouroboros-consensus-0.1.0.0-YOEuCz1reE2yr064xJ6cY", srcLocModule = "Ouroboros.Consensus.Storage.FS.IO", srcLocFile = "src/Ouroboros/Consensus/Storage/FS/IO.hs", srcLocStartLine = 82, srcLocStartCol = 23, srcLocEndLine = 82, srcLocEndCol = 38}),("rethrowFsError",SrcLoc {srcLocPackage = "ouroboros-consensus-0.1.0.0-YOEuCz1reE2yr064xJ6cY", srcLocModule = "Ouroboros.Consensus.Storage.FS.IO", srcLocFile = "src/Ouroboros/Consensus/Storage/FS/IO.hs", srcLocStartLine = 46, srcLocStartCol = 38, srcLocEndLine = 46, srcLocEndCol = 55}),("hGetSome",SrcLoc {srcLocPackage = "ouroboros-consensus-0.1.0.0-YOEuCz1reE2yr064xJ6cY", srcLocModule = "Ouroboros.Consensus.Storage.FS.API", srcLocFile = "src/Ouroboros/Consensus/Storage/FS/API.hs", srcLocStartLine = 220, srcLocStartCol = 16, srcLocEndLine = 220, srcLocEndCol = 39})], fsLimitation = False}
cardano-node: FsInsufficientPermissions for C:\Users\patk3\AppData\Roaming\Daedalus Flight\chain\protocolMagicId: The process cannot access the file because another process has locked a portion of the file. at CallStack (from HasCallStack):
  ioToFsError, called at src/Ouroboros/Consensus/Storage/FS/IO.hs:86:41 in ouroboros-consensus-0.1.0.0-YOEuCz1reE2yr064xJ6cY:Ouroboros.Consensus.Storage.FS.IO
  handleError, called at src/Ouroboros/Consensus/Storage/FS/IO.hs:82:23 in ouroboros-consensus-0.1.0.0-YOEuCz1reE2yr064xJ6cY:Ouroboros.Consensus.Storage.FS.IO
  rethrowFsError, called at src/Ouroboros/Consensus/Storage/FS/IO.hs:46:38 in ouroboros-consensus-0.1.0.0-YOEuCz1reE2yr064xJ6cY:Ouroboros.Consensus.Storage.FS.IO
  hGetSome, called at src/Ouroboros/Consensus/Storage/FS/API.hs:220:16 in ouroboros-consensus-0.1.0.0-YOEuCz1reE2yr064xJ6cY:Ouroboros.Consensus.Storage.FS.API[35m[cardano-wallet.main:Notice:10][0m [2020-04-03 11:16:15.76 UTC] Starting clean shutdown...
[cardano-wallet.main:Debug:3] [2020-04-03 11:16:15.76 UTC] Logging shutdown.
```

Full Daedalus logs (node.log is where Daedalus outputs combined cardano-wallet and cardano-node log streams):
[logs-2020-04-03T111617.0947Z.zip](https://github.com/input-output-hk/ouroboros-network/files/4434423/logs-2020-04-03T111617.0947Z.zip)

**Comment by dcoutts** [comment] 2020-04-05 17:39
Note this bit of the error message:
```
chain\protocolMagicId: The process cannot access the file because another process has locked a portion of the file.
```
This is a Win32 error message

https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/18d8fbe8-a967-4f1c-ae50-99ca8e491d2d
```
0x00000020   ERROR_SHARING_VIOLATION
The process cannot access the file because it is being   used by another process.

0x00000021 ERROR_LOCK_VIOLATION
The process cannot access the file because another process has locked a portion of the file.
```

Notice also that the error happens with `hGetSome` and not on file opening. This means it is not a whole-file sharing violation (with another process having the file open for writing). Also it would otherwise be `ERROR_SHARING_VIOLATION`. This looks like a lock on the content of the file (i.e. using `LockFile` or `LockFileEx`).

The node itself never uses this kind of locking. It only uses whole-file write locks (sharing modes).

A quick google suggests that the cause of this is sometimes due to virus scanners or backup software locking files temporarily. If this is the real cause, I should not that this is completely insane to break 3rd party software in this way. File locking is supposed to be a cooperative arrangement.

**Comment by mrBliss** [comment] 2020-04-06 07:04
Note that consensus locks exactly that `protocolMagicId` file to ensure that the database is never opened by more than one node at once. People have done that in the past, leading to weird errors. We use [`tryLockFile`](https://hackage.haskell.org/package/filelock-0.1.1.4/docs/System-FileLock.html#v:tryLockFile) for this.

I expect that you're indeed using the same database by two nodes. The error you're seeing is not the one we expect, though. At least on Linux we get a more helpful one:

> The db is used by another process. File "chain/protocolMagicId" is locked

I'm assuming that's because on Linux we can still read a locked file, whereas we can't on Windows.

Next steps:
* Confirm that my hypothesis is true: on Windows, a locked file cannot be read from a process other than the one that locked it.
* If so, (first thing that comes to mind) catch that exception in [`checkDbMarker`](https://github.com/input-output-hk/ouroboros-network/blob/954dcc08be8838a2e3a8d1b4231e6320c7839931/ouroboros-consensus/src/Ouroboros/Consensus/Node/DbMarker.hs#L71) (use `fsErrorNo = Just (Errno 13)` to identify it) and rethrow it as [`DbMarkerError.DbLocked`](https://github.com/input-output-hk/ouroboros-network/blob/954dcc08be8838a2e3a8d1b4231e6320c7839931/ouroboros-consensus/src/Ouroboros/Consensus/Node/DbMarker.hs#L138). Alternatively, lock (`lockDbMarkerFile`) before checking it.

**Comment by kderme** [comment] 2020-04-06 07:52
> Confirm that my hypothesis is true: on Windows, a locked file cannot be read from a process other than the one that locked it.

Yes that's true. According to filelock doc:

> -- It is not recommended to open or otherwise use lock files for other
-- purposes, because it tends to expose differences between operating systems.
-- For example, on Windows 'System.IO.openFile' for a lock file will fail when
-- the lock is held, but on Unix it won't.

That's why we first access the dbMarket and then we lock it. This is a bit weird though and can leave to errors in unexpected places, like reported. I prepared a fix, which separates the dbMarker from the dbLock and uses a second file as a lock. Also my fix attemps a number of times to take the lock and sleeps at the internal, before it gives up and throws the exception. This could also fix cases where a previous node has not completely shut down yet or third party software have locked the file for small durations.

**Comment by mrBliss** [comment] 2020-04-06 08:07
> > Confirm that my hypothesis is true: on Windows, a locked file cannot be read from a process other than the one that locked it.
> 
> Yes that's true. According to filelock doc:
> 
> > -- It is not recommended to open or otherwise use lock files for other
> > -- purposes, because it tends to expose differences between operating systems.
> > -- For example, on Windows 'System.IO.openFile' for a lock file will fail when
> > -- the lock is held, but on Unix it won't.
> 
Great, thanks for confirming this.

> That's why we first access the dbMarket and then we lock it. This is a bit weird though and can lead to errors in unexpected places, like reported. I prepared a fix, which separates the dbMarker from the dbLock and uses a second file as a lock. Also my fix attemps a number of times to take the lock and sleeps at the internal, before it gives up and throws the exception. This could also fix cases where a previous node has not completely shut down yet or third party software have locked the file for small durations.
> 
> #1906

Oh, one step at a time and keep things simple for now: we don't know yet whether retries are necessary. If they are, we can introduce them, but I wouldn't unless we have _clear evidence_ that it is needed (and this ticket is not, IMO).

**Comment by mrBliss** [comment] 2020-04-06 08:31
> Oh, one step at a time and keep things simple for now: we don't know yet whether retries are necessary. If they are, we can introduce them, but I wouldn't unless we have _clear evidence_ that it is needed (and this ticket is not, IMO).

Oops, I just reread the title of the ticket "Rapid cardano-node **restart** ...". My apologies, I was mistaken. There _is_ evidence the retries are needed.

**Comment by edsko** [comment] 2020-04-06 08:42
Just for my peace of mind: the ticket suggests that the exception is only thrown on _rapid_ restarts. I don't fully understand how this could happen; a file lock isn't like a socket which incurs a delay on closing; I would have assumed that releasing a lock is a synchronous operation, and so if the the node has been shut down, the lock must have been released and there is no need for exponential back-off. The ticket does indeed suggest that this line of reasoning is not true, but I'd like to understand better why.

**Comment by mrBliss** [comment] 2020-04-06 08:47
> Just for my peace of mind: the ticket suggests that the exception is only thrown on _rapid_ restarts. I don't fully understand how this could happen; a file lock isn't like a socket which incurs a delay on closing; I would have assumed that releasing a lock is a synchronous operation, and so if the the node has been shut down, the lock must have been released and there is no need for exponential back-off. The ticket does indeed suggest that this line of reasoning is not true, but I'd like to understand better why.

@nikolaglumac Could you confirm that the problem doesn't occur with a "slow restart"?

**Comment by nikolaglumac** [comment] 2020-04-06 11:42
@edsko @mrBliss I am still trying to figure that out. Will let you know once I analyze all the logs.
It could even be the case of us trying to start the node before it fully exited the first time...

**Comment by dcoutts** [comment] 2020-04-06 21:10
>  I would have assumed that releasing a lock is a synchronous operation, and so if the the node has been shut down, the lock must have been released and there is no need for exponential back-off. The ticket does indeed suggest that this line of reasoning is not true, but I'd like to understand better why.

Windows hates you and all developers everywhere. No this is not true. Windows _lazily_ releases these file locks. So you cannot rely on waiting for the process to terminate to guarantee that all the locks are released. Yes a Windows process can have locking interfere with another instance of itself even when only one instance is running at once!

That said, we do not need to poll on the file lock, or use exponential backoff, we can use a blocking lock acquisition with a modest timeout. The lazy file lock releases are moderately prompt. I'd expect a couple seconds should be more than enough.

**Closed** 2020-04-24 11:23 UTC
Labels: Windows, consensus
