### ISSUE TITLE
Convert Byron ledger to Shelley ledger and check in-memory size

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1404] opened 2020-01-07 09:22 UTC

**Comment by edsko** [comment] 2020-05-12 10:17
Conversion will be done as part of #2072. This ticket is only about the memsize check.

**Comment by mrBliss** [comment] 2020-06-02 11:47
The size of the ledger data structure is the responsibility of the ledger(-specs) team.

**Comment by mrBliss** [comment] 2020-07-20 07:38
It's much easier for consensus (than `cardano-ledger-specs`) to get our hands on a mainnet Byron ledger and convert it to a Shelley one.

**Comment by kderme** [comment] 2020-07-20 13:00
It's not clear to me how I should translate the `HeaderState`.  The function we discussed `translateLedgerStateByronToShelley` translated only the `LedgerState`.

**Comment by kderme** [comment] 2020-07-21 08:27
When I translate the ledger after block 335263654d897c7c6b3dfe22b412889c973191d1c5d71269a92fc3cda9976105 (2 days ago) the size changes from 17930999 words to 36930043.

However when I call `noUnexpectedThunks []` after the translation I get 
```
UnexpectedThunk (UnexpectedThunkInfo {unexpectedThunkContext = 
["GenDelegPair","Map","DState","DPState","LedgerState","EpochState","NewEpochState","LedgerState"], 
unexpectedThunkCallStack = [("$dmnoUnexpectedThunks",SrcLoc {srcLocPackage = "shelley-spec-ledger-0.1.0.0-inplace", 
srcLocModule = "Shelley.Spec.Ledger.Keys", srcLocFile = "src/Shelley/Spec/Ledger/Keys.hs", srcLocStartLine = 280, 
srcLocStartCol = 10, srcLocEndLine = 280, srcLocEndCol = 50}),("noUnexpectedThunks",SrcLoc {srcLocPackage = "cardano-
prelude-0.1.0.0-inplace", srcLocModule = "Cardano.Prelude.GHC.Heap.NormalForm.Classy", srcLocFile = 
"src/Cardano/Prelude/GHC/Heap/NormalForm/Classy.hs", srcLocStartLine = 186, srcLocStartCol = 31, srcLocEndLine = 186, 
srcLocEndCol = 56})], unexpectedThunkClosure = Just "ThunkClosure {info = StgInfoTable {entry = Nothing, ptrs = 2, nptrs = 0, 
tipe = THUNK_2_0, srtlen = 0, code = Nothing}, ptrArgs = [0x0000004216f0e030,0x0000004216f0e000], dataArgs = []}"})
```
When I call it before the translation it starts spamming `closurePtrs: Cannot handle type CONSTR_NOCAF yet` without end. This seems to be recently fixed https://gitlab.haskell.org/ghc/ghc/-/issues/16624

Note I take this ledger using the chaing db api `getCurrentLedger`. I also added bang patterns to have everything in whnf.

**Comment by kderme** [comment] 2020-07-21 08:58
> When I call it before the translation it starts spamming closurePtrs: Cannot handle type CONSTR_NOCAF yet without end. This seems to be recently fixed https://gitlab.haskell.org/ghc/ghc/-/issues/16624

Correction: actually it returns successfully with `NoUnexpectedThunks` after a while, but prints these errors on stderr. I guess this is just a red herring.

**Comment by mrBliss** [comment] 2020-07-21 09:47
> 17930999 words to 36930043.

So Byron: 137 MiB, Shelley: 282 MiB. That's more than twice as big.

We should report these findings to the ledger specs team.

Those annoying `closurePtrs` warnings are indeed expected.

I think that thunk in the Shelley ledger is caused by accidental use of `Data.Map` instead of `Data.Map.Strict` in the ledger:

```
shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Delegs.hs:30:import Data.Map as Map
shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/API/Wallet.hs:15:import Data.Map (Map)
shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/API/Wallet.hs:16:import qualified Data.Map as Map
shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Serialization.hs:91:import Data.Map (Map)
shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Serialization.hs:92:import qualified Data.Map as Map
```

@kderme Can you fix that in `cardano-ledger-specs` (replace with `Data.Map.Strict` and check for thunks again)?

**Comment by kderme** [comment] 2020-07-21 09:52
The 2 time plus increase seems persistent throughout the chain:
45c2185719fb3f94bd112e69bde2c006e593e6d8e06f6175fc351141034a83f7 (2017/12/22 21:44:31 UTC)  3319020 ->  7476439

7d0a99accb4be05906c8e20253cddda11f5aa6983de853923aad1b7b2233259d (2018/01/06 21:44:31 UTC)  4737156 -> 10687199
 
736e8429a6c547ff7a11d837c8f0695a271367a6538bee528faffdec3ff6cb90 (2017/10/09 05:08:11 UTC)   565344 -> 1201766

**Comment by kderme** [comment] 2020-07-21 11:08
Bumping c-l-s to 9dc2eab from b26d5ee, there is a huge memory improvement on shelley ledger state: 
<pre>
hash                                                              Byron     Shelley-old   Shelley-new
335263654d897c7c6b3dfe22b412889c973191d1c5d71269a92fc3cda9976105  17930999  36930043      20043849
45c2185719fb3f94bd112e69bde2c006e593e6d8e06f6175fc351141034a83f7  3319020   7476439       3706254
7d0a99accb4be05906c8e20253cddda11f5aa6983de853923aad1b7b2233259d  4737156   7476439       5281758
736e8429a6c547ff7a11d837c8f0695a271367a6538bee528faffdec3ff6cb90  565344    1201766       648324
</pre>
I see there is another optimization at 33e4ffa, but I get compile errors when I bumb ouroboros-consensus.
The thunk persists on 9dc2eab.

**Comment by kderme** [comment] 2020-07-22 08:14
So I tried to understand what causes this thunk and it was quite surprising. It seems the Data.Map and Data.Map.Strict share the same type `Map`. What differs are the functions exported by Strict, which give the following guarantees
```
--  - If all values stored in all maps in the arguments are in WHNF, then all
--    values stored in all maps in the results will be in WHNF once those maps
--    are evaluated.
```

Now aeson uses  the lazy versions of the functions to create the Map  from a JSON file. This means the result can have values not in whnf, even if a user has imported the Strict version.

This is exactly what happens with the `sgGenDelegs` and other fields of genesis. Later, during translation this field with thunks is used by the ledger state.

**Comment by kderme** [comment] 2020-07-22 08:16
Probably a way to fix it is to go through all values of these maps and force them to whnf.

**Comment by mrBliss** [comment] 2020-07-22 08:17
Nice find! There is [`forceElemsToWHNF`](https://github.com/input-output-hk/cardano-prelude/blob/eee27bd6697d5ab1b943ee9c50ee638bde009c81/src/Cardano/Prelude/Strict.hs#L17).

**Comment by kderme** [comment] 2020-07-22 08:25
> Nice find! There is forceElemsToWHNF.

Yes this fixed it. I will open a pr

**Comment by mrBliss** [comment] 2020-07-23 08:54
Closing, thanks to https://github.com/input-output-hk/ouroboros-network/issues/1404#issuecomment-661791094

**Comment by kderme** [comment] 2020-07-24 10:30
I run the same heap size tests https://github.com/input-output-hk/ouroboros-network/issues/1404#issuecomment-661791094 on current ouroboros-consensus head, and I see that there is a constant increase around 3M words on the same translated ledger states. For example 20043849 is now 23525616. 3706254 is now 7188021.  5281758 is now 8763525. Even when I translate the genesis ledger I get 3876704, while on Byron it is 334064.

**Comment by kderme** [comment] 2020-07-24 11:11
Eventually the new results https://github.com/input-output-hk/ouroboros-network/issues/1404#issuecomment-663474458 are the correct. Previously I had used a Shelley genesis from a mainnet-candidate, which has a much smaller "epochLength" than the one used in mainnet. I'd say that even if the increase of 3M seems too big for the initial parts of the chain, it's not that big relatively, for the last parts (which is what actually matters).

**Comment by mrBliss** [comment] 2020-07-24 11:34
I believe this is because of the [overlay schedule](https://github.com/input-output-hk/cardano-ledger-specs/blob/a790fb38cced04d8d8a9aeacc2a761717f11f94e/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/LedgerState.hs#L592), which contains an entry for each slot in the epoch. When the epoch size increases, we expect this map to increase too.

A few months ago, I [made](https://github.com/input-output-hk/cardano-ledger-specs/pull/1378) the serialisation of this overlay schedule already more compact, maybe we should do the same thing or something similar for the in-memory representation too.

Because it's just [round-robin](https://github.com/input-output-hk/cardano-ledger-specs/blob/a790fb38cced04d8d8a9aeacc2a761717f11f94e/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/LedgerState.hs#L1027), maybe the in-memory representation could just be a function instead of a map.

**Comment by kderme** [comment] 2020-07-24 11:41
Recap: ouroboros-consensus on adae68e6c2b6d8a02646ff03b557ccc03a6655c8 with `mainnet` cluster configurations in https://hydra.iohk.io/build/3596468/download/1/index.html. Heap size in MiB, translation time in sec: 
<pre>
hash                                                              Byron Shelley time
335263654d897c7c6b3dfe22b412889c973191d1c5d71269a92fc3cda9976105  17.1  22.4    4.1
45c2185719fb3f94bd112e69bde2c006e593e6d8e06f6175fc351141034a83f7  3.2   6.8     0.7
7d0a99accb4be05906c8e20253cddda11f5aa6983de853923aad1b7b2233259d  4.5   8.3     1
</pre>

**Comment by kderme** [comment] 2020-07-24 14:59
Time at f1c094627fc45e6a82f9a9ad8ee722e5a6b0e239 dropped to 2.8, same size.

**Comment by mrBliss** [comment] 2020-07-27 13:29
We have measured it, but optimising it is not our responsibility, closing again.

**Closed by mrBliss** 2020-07-27 13:29 UTC
Labels: consensus, priority high, shelley ledger integration, shelley mainnet, transition
