### ISSUE TITLE
Keep _every_ snapshot of the ledger state in memory

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1936] opened 2020-04-10 09:16 UTC
At the moment, the ledger DB has a `snapEvery` parameter that tells it how often to store a snapshot of the ledger state in memory. When the ledger DB is then asked for a historical snapshot, it might have to replay some blocks, which are stored on disk. This is relatively expensive, but should also occur relatively infrequently. Ticket #1026 is about figuring out a good value for that `snapEvery` parameter, and also suggests that we might to special case some snapshots near the tip (see also https://github.com/input-output-hk/ouroboros-network/issues/1026#issuecomment-572945358). 

It is worth considering if we could just store _every_ snapshot. This would make the design of the ledger DB significantly simpler, would avoid the need for any kinds of special cases, and as a bonus, also allows simplifications in other parts of the code base; in particular, see https://github.com/input-output-hk/ouroboros-network/issues/1935#issuecomment-611950826 .

**Comment by mrBliss** [comment] 2020-04-10 14:49
@intricate Can you try to figure out how much memory keeping the last `k` snapshots of the ledger would require (just set `snapEvery` to 1) compared to the current policy (with mainnet)? You can measure the memory by profiling or by using the heap size stuff.

**Comment by kderme** [comment] 2020-07-15 19:07
Some initial results I got by using `computeHeapSize`. Probably it would make sense to compare this with the number of transactions on these blocks and test for bigger chains. However the main issue is that I met 4 closures types that are not supported: `THUNK_STATIC, FUN_STATIC, MUT_ARR_PTRS_FROZEN_CLEAN,  MUT_ARR_PTRS_FROZEN_DIRTY` which I'm not sure I supported the correct way.

![Figure_1-1](https://user-images.githubusercontent.com/11467473/87584645-7f600b80-c6e6-11ea-8e28-7d50cff1ceb4.png)

**Comment by kderme** [comment] 2020-07-20 04:51
Eventuall these closure types disappeared when I added a bang pattern for the result of `ledgerDbPush` before calling `computeHeapSize`. These are the results I got for a small part of mainnet, starting from the same snapshot at block 3a76f8bf33d854e221d958543d42293ab8ce94b4573a7b1e5d70cd345e8a9bf3.

![full](https://user-images.githubusercontent.com/11467473/87900211-5c25bb00-ca5c-11ea-97aa-f83541f22ca9.png)

![zoom2](https://user-images.githubusercontent.com/11467473/87900259-87a8a580-ca5c-11ea-8fdd-2d49e6fe7ee8.png)
![zoom1](https://user-images.githubusercontent.com/11467473/87900263-8aa39600-ca5c-11ea-8804-0d5737f75010.png)

Especially from the zoomed graphs, it's easy to see that the number of transactions in the blocks is a big factor on how much the ledgerDB inscreases in size. 

I also created the plots for the `ledgerDBCurrent` field of the LedgerDB.
![full](https://user-images.githubusercontent.com/11467473/87900296-ab6beb80-ca5c-11ea-9659-2ebe523fa233.png)

As expected this does not depend on `snapEvery`. On the other hand, the `ledgerDBBlocks` size looks like a step function, with big increases every `snapEvery` blocks (when new snapshots are taken).

![reduced](https://user-images.githubusercontent.com/11467473/87900413-f554d180-ca5c-11ea-82a2-0ce5479349b7.png)
![reduced-zoom-2](https://user-images.githubusercontent.com/11467473/87900415-f685fe80-ca5c-11ea-8edb-f43d861af6b5.png)

**Comment by kderme** [comment] 2020-07-20 05:01
It may look from the above, that the size of ledgerDB increases very fast, however this happens only because we have focused so far on the period before saturation. During this period, the `ledgerDBBlocks` length increases by one for each block applied. After saturation (around k blocks) old entries are pruned, so the size increases much slower or there are periods it even decreases. The plots below start from the same block as before, but span up to the end of epoch 17. Note that epoch 17 is the epoch with the most number of transactions on mainnet.

![full](https://user-images.githubusercontent.com/11467473/87900739-e9b5da80-ca5d-11ea-87ec-153c86bea399.png)
![zoom2](https://user-images.githubusercontent.com/11467473/87900740-eae70780-ca5d-11ea-9a8d-320eea2804e0.png)


For snapEvery = 20, 100 and k, there are drops with period snapEvery which collide with old snapshots being pruned. For snapEvery = 1, a snapshot is pruned on each step, so the difference on size not only depends on current transactions but also on transactions k blocks before. That's why we don't see here any corelation with the number of transactions. 

These are the plots for `ledgerDBCurrent` and `ledgerDBBlocks` on the same period:
![ledgerDBBlocks](https://user-images.githubusercontent.com/11467473/87900941-66e14f80-ca5e-11ea-950e-bf52a160663a.png)
![ledgerDBCurrent](https://user-images.githubusercontent.com/11467473/87900942-68ab1300-ca5e-11ea-94bc-2d4fa3676662.png)

It seems that after saturation the difference of `ledgerDB` for different snapEvery stabilizes or increases very slowly. From the results so far it seems that for the k used in mainnet the overhead of snapEvery = 1 is pretty small. However for bigger k's the difference should be bigger. It is also interesting to see what happens to this difference towards the tip of mainnet. I'm currently running these tests and waiting for results

**Comment by kderme** [comment] 2020-07-21 07:35
These are the results for around 40k blocks towards the tip of mainnet. 

![last](https://user-images.githubusercontent.com/11467473/88025403-e80f1400-cb3c-11ea-98e2-7602649fd94b.png)

The overhead we get seems to be correlated with the number of transactions in the last k blocks.
Linear regression shows this better:

![linear](https://user-images.githubusercontent.com/11467473/88025761-71264b00-cb3d-11ea-84d4-59c0ba240073.png)

It's also worth noting that the overhead hasn't increased since epoch 17 (around 1M words). This means that accumulated utxo, doesn't really add up to the overhead and it's mainly the movement in the last k blocks that matters. Here is the same plot for epoch 17:
![overhead](https://user-images.githubusercontent.com/11467473/88025970-c9f5e380-cb3d-11ea-9a8f-18c76f0011c2.png)

**Comment by mrBliss** [comment] 2020-07-21 09:33
Great! So if we take 1,200,000 GHC words as the max overhead from the graphs, that's 1,200,000 * 8 bytes ~= 9 MiB, which is acceptable. Thanks for these graphs.

**Comment by mrBliss** [comment] 2020-07-23 14:45
Closing this in favour of #2440 and #1935.

**Closed by mrBliss** 2020-07-23 14:45 UTC
Labels: consensus, enhancement
