### ISSUE TITLE
Distinguish fatal from non-fatal exceptions in connection threads

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#798] opened 2019-07-19 11:07 UTC
For each client/server-protocol pair, a node has (in the normal case) an open connection with a corresponding thread. When an exception is thrown in that thread, the connection and thread are simply restarted. This is a good default behaviour, as a transient error or adversarial behaviour should not bring down the whole node. However, some exceptions, e.g., file-system errors, can be fatal and *should* shut down the whole node.

We need a way to distinguish between fatal and non-fatal errors and respond appropriately (that should be done here: https://github.com/input-output-hk/ouroboros-network/pull/796#discussion_r305297486).

@dcoutts suggests taking a function `SomeException -> Bool` to determine whether an exception is fatal or not.

The network layer can take such a function, but the consensus layer is free to implement the pattern described here: https://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Exception.html#t:Exception.

The consensus layer will most likely provide such a function in the `NodeParams` record, which is passed to the network layer in `Ouroboros.Consensus.NodeNetwork`.

**Comment by mrBliss** [comment] 2019-08-27 15:02
See https://github.com/input-output-hk/ouroboros-network/pull/773#discussion_r317491893

**Comment by coot** [comment] 2019-11-13 11:14
This is realated to #1127 and one will be able to fix this by designing an `ErrorPolicy` when #1127 is merged.

**Comment by edsko** [comment] 2019-11-19 08:19
Closed in https://github.com/input-output-hk/ouroboros-network/pull/1241 .

**Closed by edsko** 2019-11-19 08:19 UTC
Labels: consensus, networking, priority high
