### ISSUE TITLE
Shorten the STM transaction that produces a new block

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#786] opened 2019-07-17 13:46 UTC
Quoting from https://github.com/input-output-hk/ouroboros-network/pull/777#pullrequestreview-262410795 (and Slack):

Duncan:
> I'm also slightly concerned about how big and long running this STM transaction is now. I wonder if we can make it shorter, perhaps in a subsequent PR. Note that it looks like the `runProtocol` uses do not have to be in the same STM tx. They're only in STM because of access to the PRNG. So the use of `withSyncState` might only have to cover grabbing snapshots of the current chain and ledger state, and returning those two along with the consistent mempool snapshot. Then the `checkIsLeader` and `produceBlock` actions can happen in a subsequent STM tx that only changes the PRNG tvar. I don't think this changes the nature or duration of the remaining race condition.

Thomas:
> `checkIsLeader` (inside `runProtocol`) refers to `ledgerState` (brought in scope by `l@ExtLedgerState{..} <- ChainDB.getCurrentLedger chainDB`). Don't we want this to be in the same transaction as the one that obtains the current ledger?

Duncan:
> That  ledger state is a pure value right? It's no longer mutable at that point. So we grab the snapshots of ledger, chain tip and mempool consistently in one STM tx, but then once we have immutable snapshots we can operate on them outside the tx.

The code in question starts here: https://github.com/input-output-hk/ouroboros-network/blob/74b5c33fc105eca2292177dda9c6ad6058bf876c/ouroboros-consensus/src/Ouroboros/Consensus/Node.hs#L316

**Comment by edsko** [comment] 2019-11-08 08:53
The only thing we could remove from the transaction is the final call to `produceBlock`. However, it's not a high priority.

**Comment by edsko** [comment] 2020-01-10 12:20
Turns out, we need to do this in order to (after a chain of dependencies) solve #1437. Current plan is to proceed as follows:

1. Atomically get the current fragment and ledger.
2. Check if we are the leader (this does not need STM).
3. If we are the leader, get a snapshot of the mempool that is consistent with that ledger state. This does not need to live in STM, but does depend on implementing https://github.com/input-output-hk/ouroboros-network/issues/1438 first.
4. Finally, produce a block. 

With a bit of luck this means we can get rid of the whole `runProtocol`/`ProtocolM` infrastructure (or at least simplify it).

Then after we implement https://github.com/input-output-hk/ouroboros-network/issues/1440, this will change to

1. Get current fragment (as an STM transaction that does a single thing)
2. Get the ledger state for the right point
3. Check if we are the leader
4. Get a snapshot of the mempool
5. Produce the block

This means we might end up producing a block for a fork that will not be used because meanwhile we switched to a different one, but that's okay. 

Note that (2) can fail if we switched to _much_ longer fork and the ledger state isn't reproducible from the ledger DB anymore. If this happens, we can just give up on producing a block I think.

**Comment by edsko** [comment] 2020-01-10 12:31
Marking as high priority since required to fix a bug (#1437).

**Closed** 2020-01-10 17:04 UTC
Labels: byron, consensus, priority high
