### ISSUE TITLE
Shelley integration: bounds in terms of slots should be 20k, not 2k

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1955] opened 2020-04-15 15:28 UTC

**Comment by nc6** [comment] 2020-04-16 08:52
(Trying to capture understanding from the meeting last night)

I think the issue is wider than this - we need to think precisely what it is that we're expressing. In most cases, I think we are using the slot bound as:

Number of slots in which, under correct operation of the system, we must have seen `k` blocks within.

For Classic this is 2k, because we expect a block in every slot (our `f`, or "active slot coefficient" is 1) and our chain quality threshold is 1/2.

In Praos, per "Parametrizing Praos", it looks like we're looking at an `f` of 0.05. But from `f` we need to calculate `\tau` (which the paper calls the "speed coefficient", I think?). The Praos paper seems to calculate `\tau = c\alpha / 4`, where `c = f(1-f)^\Delta`.

- `\alpha` is related to the adversary. I believe that it represents the maximum proportion of the stake that an adversary is allowed to control throughout the lifetime of the system. We've frequently talked of the adversary controlling no more than half of the stake, so I'm going to assume this is 0.5
- `\Delta` is the maximum message delay expressed in slots. I'm going to assume that this correlates to the number of slots late a block can arrive, although this is probably a very broad assumption.

So supposing `\Delta` is 1 (which it sounds like we're aiming for?) then we have `\tau = 0.009375`, and hence we're guaranteeing (by the chain growth property) to produce basically 20 blocks in every k slots. So to guarantee we are `k` blocks deep we would need our "slots equivalent" to be around 107k.

Which seems a very big number.

I don't know what the consequences are of picking a `\tau` in another way are. Guess we need to tlk to the researchers about this.

**Comment by edsko** [comment] 2020-04-16 10:33
We really need to compare notes with @brunjlar and co.

**Comment by nfrisby** [comment] 2020-04-17 14:29
(Just to qualify this Issue's title: we're still iterating on whether or not 20k is correct.)

**Comment by edsko** [comment] 2020-04-22 07:07
Note that this cannot be a static value: it will depend on the value of `f`.

**Comment by edsko** [comment] 2020-04-22 09:43
Update: thankfully the value of `f` will (for now at least) not be updatable.

**Comment by mrBliss** [comment] 2020-04-24 11:02
It should *also* be fixed here: https://github.com/input-output-hk/ouroboros-network/blob/eec4a136bb51d882ab4cf4de552f1ce978459f56/ouroboros-consensus-shelley/src/Ouroboros/Consensus/Shelley/Protocol.hs#L411

**Comment by nc6** [comment] 2020-05-26 08:19
We should avoid having the globals created in two places... I'll review and try to rationalise this.

**Comment by mrBliss** [comment] 2020-06-02 11:40
Check this with @JaredCorduan

**Comment by mrBliss** [comment] 2020-06-02 11:42
Code in question: https://github.com/input-output-hk/ouroboros-network/commit/2f1f91173a706077883266eee3bb480aaeac3748#diff-7069f07e06fe5b852aa8fd03993cc47fR415-R416
Seems `k` and `f` should be switched? @nc6

**Comment by mrBliss** [comment] 2020-06-05 06:58
Fixed by #2202, #2219, and #2220.

**Closed by mrBliss** 2020-06-05 06:58 UTC
Labels: bug, consensus, priority high, shelley mainnet, shelley testnet
