### ISSUE TITLE
Immutable DB: allow streaming from and to exclusive bounds

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#548] opened 2019-05-23 11:21 UTC
Currently the ImmutableDB only allows streaming from and to an inclusive bound (or an open bound). However, the ChainDB that is built on top of the ImmutableDB (and the VolatileDB) allows streaming from and to an _exclusive_ bound (in addition to an inclusive bound).

When the ChainDB has to stream from the ImmutableDB with an exclusive lower bound, it currently uses an inclusive lower bound and just ignores the first streamed block. Similarly for the upper bound, the block corresponding to the exclusive upper bound will be read and ignored. This has a cost of reading one extra block whenever an iterator is opened and reading one extra block before the iterator is exhausted.

Adding support for exclusive bounds to the ImmutableDB will avoid this extra cost. It is likely we can replace reading the first block by seeking past it. Open question: what about the (EBB) hash?

**Comment by edsko** [comment] 2019-05-24 06:45
@mrBliss Is this a duplicate of #369 ?

**Comment by mrBliss** [comment] 2019-05-24 06:57
Ah, indeed.

**Comment by mrBliss** [comment] 2020-03-31 09:36
Task for myself: is the extra cost still there? If not, close this issue.

**Comment by mrBliss** [comment] 2020-04-10 11:52
There is still a cost.

The ChainDB takes care of the exclusive *upper* bound by checking the next thing the ImmutableDB iterator will stream against the exclusive end bound, closing the iterator in case it matches (see #1938). This is quite cheap, the block corresponding to the exclusive end bound will not be read from disk. There's a hash equality check for each block and one extra secondary index entry will be obtained from the cache (unless it happens to be in the next chunk, then there might be an unnecessary cache miss).

However, the exclusive *lower* bound has a higher cost:
https://github.com/input-output-hk/ouroboros-network/blob/d94f6061506a4a96d636d525726b54bb5f170977/ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/ImmDB.hs#L462
The block/header corresponding to the exclusive lower bound is read from disk and discarded.

Fortunately, the BlockFetchServer only uses inclusive bounds, so we're not incurring the cost often.

**Comment by edsko** [comment] 2020-04-21 07:29
An alternative approach here might be to add a `skip` API call to the iterator API. This would be a simple extension, independently useful, and would make the current implementation of exclusive lower bounds basically free.

**Comment by mrBliss** [comment] 2020-04-21 07:29
The ChainDB.Reader uses exclusive lower bounds and incur the cost here: https://github.com/input-output-hk/ouroboros-network/blob/a5ca95890f3d4a0c37ea017b5a96f309e6f3b4da/ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/ImmDB.hs#L551

**Closed** 2020-09-11 11:36 UTC
Labels: chain db, consensus, enhancement, immutable db, optimisation
